services:
  app:
    image: payu-payments:latest
    build: .
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=production
      - URL=${URL}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - DRIVER=${DRIVER}
    networks:
      - my-network
    depends_on:
      - database

  database:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - my-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
networks:
  my-network:
