services:
  app:
    image: payu-payments:latest
    build: .
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=production
      - URL=jdbc:postgresql://database:5432/mydb
      - DB_USER=postgres
      - DB_PASSWORD=yourpassword
      - DRIVER=org.postgresql.Driver
    networks:
      - my-network
    depends_on:
      - database
    restart: on-failure

  database:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", postgres, "-d", "mydb" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./sql/migration:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
networks:
  my-network:
